### ISSUE TITLE
2.7 Support

### ISSUE THREAD

**Issue by spigelli** [pwwang/python-varname#1]
Changed some things so that it'll work on python 2.7. Is it worth submitting PR?

**Comment by pwwang** [comment]
Since python 2.7 has retired. I did not plan to support it at the very beginning. I encourage you to submit a package, maybe called `python-varname27`, for legacy support, instead of submitting a PR to this one.

**Comment by pwwang** [comment]
Closing this now since python2.7 will not be supported.
