### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by elliotgunton** [pwwang/python-varname#116]
Hey @pwwang! Just creating an issue for awareness - I tried adding 3.13 to Hera's cicd https://github.com/argoproj-labs/hera/pull/1232, but found the 3.13 job failing with the error: `varname.utils.VarnameRetrievingError: Couldn't retrieve the call node`. The same happens when running `make ci` locally.

It seems there's a compatibility issue with 3.13 for `varname` (as the rest of the Python versions work fine, so I don't think #107 applies). I can help investigate when I have time. Thanks!

**Comment by pwwang** [comment]
Can you give [v0.13.4](https://github.com/pwwang/python-varname/releases/tag/0.13.4) a try?

**Comment by elliotgunton** [comment]
Hey, the new version has the same error ([ci run here](https://github.com/argoproj-labs/hera/actions/runs/11272252409/job/31346787366?pr=1232))

**Comment by pwwang** [comment]
Try [v0.13.5](https://github.com/pwwang/python-varname/releases/tag/0.13.5).
