### ISSUE TITLE
Credit section in the README/docs

### ISSUE THREAD

**Issue by pwwang** [pwwang/python-varname#19]
@alexmojaki
I want to put a credits section in the README to include both you and your `executing` project, and maybe future contributors. Do you want to find an icon for `executing`?

_Originally posted by @pwwang in https://github.com/pwwang/python-varname/pull/15#issuecomment-671504874_

**Comment by alexmojaki** [comment]
I'm open to hearing ideas for icons, but otherwise no, it's fine.

**Comment by pwwang** [comment]
I am currently using a placeholder for `executing`. Let me know if you find an icon for it later, I can replace it.
