### ISSUE TITLE
Is it possible to get the first variable name?

### ISSUE THREAD

**Issue by SmartManoj** [pwwang/python-varname#22]
from varname import varname, nameof

a = 1
b = 2
for i in (a, b):
    print(nameof(i))

**Comment by SmartManoj** [comment]
If so,
It will also solve `varname.VarnameRetrievingError: Can only get name of a variable or attribute, not Subscript(value=Name(id='l', ctx=Load()), slice=Constant(value=0), ctx=Load())`

```
from varname import varname, nameof

a = 1
b = 2
l = (a, b)
print(nameof(l[0]))

```

**Comment by alexmojaki** [comment]
Honestly you should avoid using varname if you can. What about this:

```python
a = 1
b = 2
values = dict(a=a, b=b)
for name, value in values.items():
    print(name, value)
```
