### ISSUE TITLE
Get full path of variable name?

### ISSUE THREAD

**Issue by LinqLover** [pwwang/python-varname#23]
I really like the `varname` functionality of this package. It allows me to abandon hard-coded variable names e.g. when mocking something:
```python3
from unittest.mock import patch
import datetime
patch.object(nameof(datetime), 42)
```
However, for the same reason, I'd like to be able to fill in entire "variable paths" with python-varname, too. Pseudo code:
```python3
from unittest.mock import patch
import datetime
patch(nameof(datetime.MAXYEAR), 42)
```
However, `nameof()` only returns `'MAXYEAR'` in this example. My current workaround is to write instead:
```python3
patch(f'{nameof(datetime)}.{nameof(dt.MAXYEAR)}'), 42)
```
but obviously, this is not very elegant.

Some method like `varname.pathof` for this would be a great addition IMO!
Other examples:
```python
> pathof(x)
'x'
> pathof(x.y)
'x.y'
> pathof(x.y.z)
'x.y.z'
> pathof(x.y.z())
varname.VarnameRetrievingError
```

**Comment by alexmojaki** [comment]
This could definitely be added. Get the argument node, make sure it only consists of Name and Attribute nodes, and construct the path manually.

You can also easily do this with `sorcery`:

```python
import sorcery

@sorcery.spell
def source(frame_info, _):
    return frame_info.get_source(frame_info.call.args[0])

assert source(max(1, 2)) == "max(1, 2)"
```

In that case the argument can be any arbitrary expression and the full source of the argument will be returned. It sounds like you don't want that but I don't really see the point of the restriction. However for varname to add that functionality it would need either a new dependency such as asttokens or it would only support it for 3.8+.

**Comment by pwwang** [comment]
If you do this:
```python
# suppose a.b.c is available
nameof(a.b.c)
```
and print the node inside `nameof`, we get:
```
Call(func=Name(id='nameof', ctx=Load()), 
     args=[Attribute(value=Attribute(value=Name(id='a', ctx=Load()), attr='b', ctx=Load()), attr='c', ctx=Load())], 
     keywords=[])
```
Possible for us to traverse the node in that `args` to retrieve the full path? We could probably add an argument:
```python
nameof(a.b.c, full=True) # 'a.b.c'
```
Any obstacles to this solution?

**Comment by alexmojaki** [comment]
Sounds good.

**Comment by pwwang** [comment]
Thank you both for proposing.

Now at 071bd5604cb7154bbd6c0e0258c4f1acf48ffb56 (v0.5.0) an argument is added to `nameof` so that one can retrieve the full name of a chain of attribute calls:
```python
a = lambda: 0
a.b = a
a.b.c = a

nameof(a) # 'a'
nameof(a.b) # 'b'
nameof(a.b, full=True) # 'a.b'
nameof(a.b.c) # 'c'
nameof(a.b.c, full=True) # 'a.b.c'
nameof(a.b.c(), full=True) # VarnameRetrievingError
x = [a, a]
nameof(x[0].b.c, full=True) # VarnameRetrievingError
```

Note that it is only applicable when source code is available and the callee's node can be retrieved by `executing`. For example, this won't work:
```python
eval('nameof(a.b.c, full=True)')
```

Closing this but feel free to re-open if any issues with this API are encountered.

**Comment by LinqLover** [comment]
Wow, very great you implemented this so fast! 👏 When will the changes arrive on pip?

One might also wonder whether `full` should be `True` by default, by that's not very important for me and probably there are compatibility reasons. :-)

**Comment by alexmojaki** [comment]
It's released, `pip install -U varname` (`python-varname` is deprecated)

**Comment by LinqLover** [comment]
Hm, then this does not work for Python 3.6 I guess :/

```
$ pip3 show varname | grep Version
Version: 0.5.0
$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from varname import nameof
>>> a = lambda: 0
>>> a.b = a
>>> a.b.c = a
>>> 
>>> nameof(a) # 'a'
'a'
>>> nameof(a.b) # 'b'
'b'
>>> nameof(a.b, full=True) # 'a.b'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/varname.py", line 208, in nameof
    return _bytecode_nameof(caller + 1)
  File "/usr/local/lib/python3.6/dist-packages/varname.py", line 358, in _bytecode_nameof
    return _bytecode_nameof_cached(frame.f_code, frame.f_lasti)
  File "/usr/local/lib/python3.6/dist-packages/varname.py", line 372, in _bytecode_nameof_cached
    "Did you call nameof in a weird way? "
varname.VarnameRetrievingError: Did you call nameof in a weird way? Without soucecode available, nameof can only retrieve the name of a single variable without any keyword arguments being passed in.
```

**Comment by pwwang** [comment]
That's interesting. The tests for 3.6 have passed in CI.
I guess it's mostly because of the REPL. @alexmojaki ?
@LinqLover Could you try it with a script: `python test.py` and see if works this way?

**Comment by alexmojaki** [comment]
Perhaps "Without soucecode available" should also say "(e.g. in the shell/REPL)" to clarify. I've seen people confused about this in many different packages that depend on source code.

**Comment by LinqLover** [comment]
Yep, REPL was the problem. I confirm that the script listed above works fine when I save it in a `test.py` file before execution. Thanks again! :-)

**Comment by pwwang** [comment]
> Perhaps "Without soucecode available" should also say "(e.g. in the shell/REPL)" to clarify. I've seen people confused about this in many different packages that depend on source code.

But such a message will confuse people when they try this:
```python
exec('nameof(...)')
```

@LinqLover the default for `full` does have some compatibility considerations. You can wrap your own nameof:
```python
my_nameof(*variables):
  nameof(*variables, caller=2, full=True)
```

**Comment by alexmojaki** [comment]
"e.g. in the shell" implies "the shell is one possible way in which sourcecode might not be available, but there are others". Maybe that can be spelled out a bit more.

"Without sourcecode available, or running in a REPL" implies that there are two separate problems.

Use of exec/eval can be given as another example of a reason why the sourcecode isn't available.

We can also make a decent guess. If they code filename is `<stdin>`, it's probably the REPL. If it's `<string>`, it's probably exec.

**Comment by pwwang** [comment]
I like that 'decent guess' idea. For _bytecode_nameof, do you think it's possible/necessary to support the full format of `nameof`? I mean if one called `nameof(a.b.c, full=True)`, it'll be `CALL_FUNCTION_KW`, but we have to walk through the instructions to skip the kwarg and find the variable.

**Comment by alexmojaki** [comment]
I think it's quite risky to play with bytecode that much, I don't recommend it.

**Comment by pwwang** [comment]
Agreed. Closing this. I will try upgrade the message according to the 'decent guess'.
