### ISSUE TITLE
How to retrieve var name from nested classes

### ISSUE THREAD

**Issue by SaeedIsa90** [pwwang/python-varname#45]
Hi,

I did not find a way to get varname if I have nested classes

e.g.

```python
class A:
    def __init__():
         self.name = varname()

class B(A):
   def __init__():
       super().__init__()

var = B() # here I have error

class C(B):
   def __init__():
       super().__init__()

var2 = C()  # also error here 
```

**Comment by pwwang** [comment]
Will these solutions work for you?

https://github.com/pwwang/python-varname/issues/40#issuecomment-763965832

**Comment by SaeedIsa90** [comment]
@pwwang yes, exactly, thanks, it worked!

Regarding the code, it was just a quick example, but you got my point :)

**Comment by SaeedIsa90** [comment]
@pwwang BTW, if I may ask you on specific varname usage

I'm trying to develop new arithmetic expressions, basically, overriding **__add__** and **__sub__**

say I have MyVar demonstrates my new var and I use varname inside it as described in the issue, so:
a = MyVar()  ==> a.name is a 
b = MyVar() ==> b.name is b

c = a + b ==> a + b will generate new MyVar() and its name using varname (inside __add__) will be c ==> c.name is c and this is **good**

till here we are good.

but if I do:
d = MyVar() ==> d.name is d
f = a + b - d  ==> 

here if I use varname inside __add__ and inside __sub__ and as you know the arithmetic operations in this case done sequentially, which means it does the + first between a and b then does the - between the results of a and b (lets call it sum_a_b) and d

in this case the sum_a_b.name is **f** and the final results of f.name is f as well.

any idea how I can tell in this case do not use varname until you do final assignment ?


Thanks in advance!
Saeed

**Comment by alexmojaki** [comment]
This sounds beyond the scope of varname. I suggest you go straight to https://github.com/alexmojaki/executing

**Comment by SaeedIsa90** [comment]
@alexmojaki ok will check it, thanks!

From my  side, I will close the issue as what @pwwang suggested worked for me, thanks!

**Comment by SaeedIsa90** [comment]
@alexmojaki I checked it and did not understand how it could help actually if you can give pointers according to above example.

Thanks in advance

**Comment by alexmojaki** [comment]
You would use executing inside `__init/add/sub__` to retrieve the node and then check if the parent node is an assignment (in which case you can set the name) or a larger expression.

**Comment by SaeedIsa90** [comment]
@alexmojaki forgive my dumb question and slow understanding, maybe I don't get and understand fully documentation there.

what is that frame?
    def __add__(self, other):
        import executing
        node = executing.Source.executing(< here > ).node
        print(node)
        return self.operator_generation(self, "+", other)

I could not follow the documentation and grab it up if you can help, appreciate it.

**Comment by SaeedIsa90** [comment]
Actually I tried this code from your tests:
added it to \__add__
`
        import executing
        import inspect
        new_node = executing.Source.executing(inspect.currentframe()).node
       
`

but both new_node.parent.parent = Assign

I could not find how it helps

**Comment by pwwang** [comment]
Maybe you can add some logic to avoid retrieving the node, but just use `varname`.

The idea is that you will need to check whether the `MyVar` object is independent (not computed/created by arithmetic operators) or not. If it is, remove the name, or set it to `None`.

Here is the code:

```python
from varname import varname

class MyVar:
    def __init__(self, val, left=None, right=None, name=None):
        # The value 
        self.val = val
        # The left var if this is from arithmetic operator
        self.left = left
        # The right var if this is from arithmetic operator
        # If both of left and right are None, meaning I am independent and 
        # constructed directly, say a = MyVar(1)
        self.right = right
        # The name of this var.
        # Allow passing in, since we may not be able to get it in some cases
        self.name = name or varname()

    def __add__(self, right):
        if self.left and self.right:
            # If I am from arithmetic operator, say a+b
            # And I am involved in another arithmetic operation
            self.name = None
        return MyVar(self.val + right.val, self, right, varname())

    def __sub__(self, right):
        if self.left and self.right:
            self.name = None
        return MyVar(self.val - right.val, self, right, varname())

a = MyVar(1)
b = MyVar(2)
c = a + b
print(c.val, c.name) # 3 'c'

c = MyVar(3)
d = a + b - c
print(d.val, d.name) # 0 'd'

print(d.left.name) # None
print(d.right.name) # 'c'
```

**Comment by alexmojaki** [comment]
Maybe in this case we should try to be less magical.

```python
class MyVar:
    def __init__(self, val):
        self.val = val
        self.name = None

    def __add__(self, right):
        return MyVar(self.val + right.val)


def set_names(variables):
    for name, value in variables.items():
        if isinstance(value, MyVar):
            value.name = name

def main():
    a = MyVar(1)
    b = MyVar(2)
    c = a + b
    set_names(locals())
    assert a.name == 'a'
    assert b.name == 'b'
    assert c.name == 'c'


main()
```

**Comment by SaeedIsa90** [comment]
Thanks a lot guys!, I will give it a try of both and see what fits more
Appreciate your help!
