### ISSUE TITLE
nameof not working inside of for loop

### ISSUE THREAD

**Issue by tbrodbeck** [pwwang/python-varname#5]
If I run this code the first call on a variable can be processed. But if I call it inside a for loop I get an error.
```python
import varname
test = {}
print(varname.nameof(test))
for i in [0]:
  print(varname.nameof(test))
```
```
test
---------------------------------------------------------------------------
VarnameRetrievingError                    Traceback (most recent call last)
<ipython-input-39-f74218a72604> in <module>
      2 print(varname.nameof(test))
      3 for i in [0]:
----> 4   print(varname.nameof(test))

~/dev/textSum/.direnv/python-3.8.3/lib/python3.8/site-packages/varname.py in nameof(*args)
    183     if not exec_obj.node:
    184         # we cannot do: assert nameof(a) == 'a' in pytest
--> 185         raise VarnameRetrievingError("Callee's node cannot be detected.")
    186 
    187     assert isinstance(exec_obj.node, ast.Call)

VarnameRetrievingError: Callee's node cannot be detected.
```
Tested on macOS Catalina with python 3.8.3

**Comment by pwwang** [comment]
Fixed at [v0.2.0](https://github.com/pwwang/python-varname/tree/0.2.0).
Feel free the reopen if you have any related questions.

**Comment by pwwang** [comment]
Any thoughts on this? Looks like recent PRs break this.

```python console
In [1]: import varname 
   ...: test = {} 
   ...: print(varname.nameof(test)) 
   ...: for i in [0]: 
   ...:   print(varname.nameof(test)) 
   ...:                                                                                                
test
---------------------------------------------------------------------------
VarnameRetrievingError                    Traceback (most recent call last)
<ipython-input-1-7b4a24e26b47> in <module>
      3 print(varname.nameof(test))
      4 for i in [0]:
----> 5   print(varname.nameof(test))
      6 

/path/to/python-varname/varname.py in nameof(_caller, *args)
    201         tuple|str: The names of variables passed in
    202     """
--> 203     node = _get_node(_caller - 1)
    204     if not node:
    205         if len(args) == 1:

/path/to/python-varname/varname.py in _get_node(caller)
    299     if exet.source.text and exet.source.tree:
    300         raise VarnameRetrievingError(
--> 301             "Couldn't retrieve the call node. "
    302             "This may happen if you're using some other AST magic at the "
    303             "same time, such as pytest, ipython, macropy, or birdseye."

VarnameRetrievingError: Couldn't retrieve the call node. 
This may happen if you're using some other AST magic at the same time, 
such as pytest, ipython, macropy, or birdseye.
```

**Comment by alexmojaki** [comment]
Looks like you're using ipython

**Comment by pwwang** [comment]
@alexmojaki 
@tbrodbeck We gave up support for ipython, and other environments where other AST magics apply. Since we can't reliably detect the ast node. See the discussions around [this](https://github.com/pwwang/python-varname/pull/14#issuecomment-668760890)

Try to switch to a normal python environment.

**Comment by alexmojaki** [comment]
I have fixed this issue in executing. `pip install -U executing` and it should be resolved.

You should still try to avoid using varname in ipython, support for it will always be somewhat shaky. I fixed this because executing is also a dependency of ipython itself now for displaying nicer tracebacks. Fortunately when executing doesn't work in that context in ipython, you just get a slightly less informative traceback, not an exception like with varname.

**Comment by pwwang** [comment]
@alexmojaki 
Which version of `executing` is supporting this?

**Comment by alexmojaki** [comment]
0.5.2, the latest version, released last night. Why do you ask? I don't think varname should require a specific version.

**Comment by pwwang** [comment]
@alexmojaki 
No, I am not requiring a specific version of `executing`. I just want a number here so that when something has the same problem, I can direct him to upgrade `executing` to `^0.5.2`.

**Comment by alexmojaki** [comment]
OK but in general encourage upgrading to the latest version. Most people won't even know they have it installed.

**Comment by pwwang** [comment]
@alexmojaki 
True. Just in case.

**Comment by mmarras** [comment]
So how to use `varname` in a loop then? 

```python
import varname 

var1 = 1
var2 = 2

for var in [var1,var2]:
    print(varname.nameof(var))
```
>>> 'var', 'var'

Of course I want 'var1', 'var2'.

**Comment by alexmojaki** [comment]
See https://github.com/pwwang/python-varname#value-wrapper and https://github.com/alexmojaki/sorcery#dict_of
