### ISSUE TITLE
Alternative nameof implementation that doesn't need source code

### ISSUE THREAD

**Issue by alexmojaki** [pwwang/python-varname#6]
I recently implemented [my own version of nameof](https://github.com/alexmojaki/nameof) just for fun after a discussion on python-ideas. I don't know if you'd want to actually use it in your library, but I thought you'd find it interesting. One cool feature is that it only uses bytecode, not source code, so it even works in the standard Python shell!

**Comment by pwwang** [comment]
Do you want to do a PR?
