### ISSUE TITLE
Can a license file be pacakaged in?

### ISSUE THREAD

**Issue by thewchan** [pwwang/python-varname#66]

**Comment by pwwang** [comment]
Packaged in what?

**Comment by thewchan** [comment]
The package itself?

**Comment by pwwang** [comment]
What for? What about putting terms inside `__init__.py`?

**Comment by pwwang** [comment]
Ah, the license was deleted at one of the commits by mistake. You are welcome to submit a PR for it with MIT license.

**Comment by pwwang** [comment]
I am Okay with `pwwang`. Thanks!

**Comment by thewchan** [comment]
Thanks, once a new release is pushed to PyPI I'll try again.
