### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by robertsdotpm** [pwwang/python-varname#81]
Hello, I was using Python varname for some of my projects enum variables which made logging much easier. But I noticed when profiling my code with cProfile there were tens of thousands of calls to various built-in functions. My code definitely doesn't do that much work. So I replaced the varname code with integers and it fixed the problem. It may have just been my code - still investigating - but this is a heads up.

**Comment by pwwang** [comment]
A piece of minimal reproducible code will give us more hints.

**Comment by pwwang** [comment]
Closing due to lacking activities.
