### ISSUE TITLE
Obtain current scope and pass into function

### ISSUE THREAD

**Issue by rirze** [pwwang/python-varname#82]
Hi, I am really appreciating your library and have used it in very helpful contexts in my development. I have a question; I'm unable to determine if the following is possible with your library:

Suppose I have a class method that takes in a class as a parameter:
```python3
class CreateSomething:
     def __init__(self, hosting_class):
           hosting_class.something = 'something'

     def create(self, hosting_class, new_value):
           hosting_class.something = new_value
```

And these methods are being called from a class like so:
```python3
class HostSomething:
      def __init__(self):
            create_something_class = CreateSomething(self)
            create_something_class.create(self, 'something else')
```

Is there a function in `varname` that could pass along the current class (`HostSomething`==`self`) to the class methods? Do you think it would be possible to make something like this:

```python3
class HostSomething:
      def __init__(self):
            create_something_class = CreateSomething()
            create_something_class.create('something else')
```

Searching online for a vanilla solution let me here: https://stackoverflow.com/a/14694234 
If you any ideas, please let me know! Thanks!

**Comment by pwwang** [comment]
That's something like `super()`, short for `super(SomeClass, self)`.
This video has a rough implementation for it: https://www.youtube.com/watch?v=X1PQ7zzltz4
The idea is similar to the "vanilla solution" you mentioned, which uses `current_frame.f_back.f_locals` to trace the local variables from the previous frame.

The core functions from `varname` handle the variable names that are explicitly given. The implementation behind the scenes is similar to the "vanilla solution". However, the variable/arguments are hidden in your case, which is out of the scope of this package.

The function you wanted can be implemented with a very simple wrapper around that "vanilla solution":

```python
import sys                                      
                                                
def get_prev_local(name):          
  # frame 1: inside fun2
  # frame 2: inside fun1             
  return sys._getframe(2).f_locals[name]        
                                                
def fun1():                                     
  self = 1                                      
  fun2()                                        
                                                
def fun2():                                     
  self = get_prev_local("self")                 
  print(self)                                   
                                                
fun1()    # prints 1                                      
```

**Comment by pwwang** [comment]
Close it for now. Feel free to reopen.
