### ISSUE TITLE
VarnameRetrievingError when I use function as part of module

### ISSUE THREAD

**Issue by EricThomson** [pwwang/python-varname#86]
I have a function that uses `argname()`, taking in variable names and returns them as strings:

```
def get_var_names(*variables):
    """
    return variable names
    """
    var_names = []
    for var_ind in range(len(variables)):
        var_name = argname(f"variables[{var_ind}]")
        var_names.append(var_name)
    return var_names
```

It works great:

`my_names= get_var_names(var1, var2)`

Returns `['var1', 'var2']`

But when I embed it in a module, let's call it `name_grabber`:

```
import namegrabber as ng
ng.get_var_names(var1, var2)
```

I get the following error:

> 
>     var_name = argname(f"variables[{var_ind}]")
>   File "C:\Users\Eric\Miniconda3\envs\my_env_name\lib\site-packages\varname\core.py", line 400, in argname
>     raise VarnameRetrievingError(
> varname.utils.VarnameRetrievingError: Cannot retrieve the node where the function is called.

Any idea what I am doing wrong here?

Note when I test it as part of `main` it works fine (when I run the script using `python -m filename` it runs great). The above error is only happening when I install things as part of a package in my dev environment using `pip install -e .` and then go in and import and use the code how I will want users to do things).

**Comment by pwwang** [comment]
Could you attach the full tracebacks?

**Comment by EricThomson** [comment]
Yes, but the above is pretty much the whole thing:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\Eric\namegrabber\namegrabber\namegrabber.py", line 17, in get_var_names
>     var_name = argname(f"variables[{var_ind}]")
>   File "C:\Users\Eric\Miniconda3\envs\namegrabber_dev\lib\site-packages\varname\core.py", line 400, in argname
>     raise VarnameRetrievingError(
> varname.utils.VarnameRetrievingError: Cannot retrieve the node where the function is called.

That's it. :/

**Comment by EricThomson** [comment]
If it matters:

I'm in miniconda (conda 4.11)
Python 3.9.13
Windows 10

I installed things locally using setup.py, with `pip install -e .` while I troubleshoot this new package I'm working on. Only dependencies right now are joblib and varname (but I also installed numpy to test out some things).

**Comment by pwwang** [comment]
What's the way you were running the final script, inside an IDE? Ipython? or just `python xxx.py`?

**Comment by pwwang** [comment]
From your description, are the following steps correct to reproduce?

1. Clone your repo
2. Install with `pip install -e .`
3. Write up a script:
```python
from ezsave import get_var_names

v1 = v2 = 1
names = get_var_names(v1, v2)
print(names)
```
4. Run it: `python script.py`

**Comment by EricThomson** [comment]
Within conda just starting python with `python`, and then typing code from the command line in the conda terminal. So I think to reproduce you should be able to. 

1. Clone
2. Install with pip install -e .
3. Run things from python command line like I said, e.g.:

python (to enter python from command line). Then in command line:

```
import ezsave as ez
var1 = 2
names = ez.get_var_names(var1)
```

The above should throw the error from the command line. This is what I've been doing.

**Comment by pwwang** [comment]
Did you say that run via raw python REPL?

**Comment by EricThomson** [comment]
For this error it was in conda Python command line, not ipython.

Uh oh.

**Comment by pwwang** [comment]
See #5 and #76

**Comment by EricThomson** [comment]
Ok so it had nothing to do with the fact that it is in a package. :) This is good to know. I'm typically working in Jupyter (ipython) so it should work fine there. I just tested it in Jupyter, as a package, and it worked fine. 

Thanks a lot for your help!
