### ISSUE TITLE
how to nameof inside a loop ?

### ISSUE THREAD

**Issue by LuisBL** [pwwang/python-varname#88]
I'm using the fantastic `varname` python package [https://pypi.org/project/varname/][1] to print python var names from inside the code:

```python
    >>> from varname import nameof
    >>> myvar = 42
    >>> print(f'{nameof(myvar)} + 8: {myvar + 8}')
    myvar + 8: 50
    >>>
```
but when I try to use it in a loop:

```python
    >>> a, b, c, d = '', '', '', ''
    >>> for i in (a, b, c, d):
        print(f'{nameof(i)}') 
    i
    i
    i
    i
    >>>
```

I do not get to print a, b, c, ...

How could I get something like this ?:

```
a 
b
c
d
```

  [1]: https://pypi.org/project/varname/

Cf: https://stackoverflow.com/questions/73840841/how-to-use-python-varname-to-get-var-names-inside-loops

**Comment by pwwang** [comment]
The first answer is correct:
https://stackoverflow.com/a/73840890/5088165
