### ISSUE TITLE
how to get arg name in sub function?

### ISSUE THREAD

**Issue by stemalomd** [pwwang/python-varname#90]
Hi, i want get argname with captured variable func_p1 in function f1, expected result is origin_name=='func_main_a',how can i do?
Traceback:
```
Traceback (most recent call last):
  File "...", line 358, in <module>
    func_main()
  File "...", line 352, in func_main
    f1()
  File "...", line 344, in f1
    origin_name = varname.argname(name)
  File "...\lib\site-packages\varname\core.py", line 448, in argname
    raise ImproperUseError(
varname.utils.ImproperUseError: 'func_p1' is not a valid argument of 'func.<locals>.f1'.
```
I tries all possible values for func= and frame= in the varname.argname parameter,but still get Error
```python
def func(func_p1):
    def f1():
        name = varname.nameof(func_p1)
        assert isinstance(name, str)
        origin_name = varname.argname(name)

    return f1


def func_main():
    func_main_a= 2
    f1 = func(func_main_a)
    f1()

func_main()
```

**Comment by pwwang** [comment]
Could you provide a prototype and the expected output?

**Comment by pwwang** [comment]
```python
def func(func_p1):
    name = varname.argname("func_p1")
    def f1():
        print(name)

    return f1


def func_main():
    func_main_a = 2
    f1 = func(func_main_a)
    f1()

func_main()  # prints "func_main_a"
```

**Comment by stemalomd** [comment]
> ```python
> def func(func_p1):
>     name = varname.argname("func_p1")
>     def f1():
>         print(name)
> 
>     return f1
> 
> 
> def func_main():
>     func_main_a = 2
>     f1 = func(func_main_a)
>     f1()
> 
> func_main()  # prints "func_main_a"
> ```

This is also the solution I'm currently using.
But I still wonder if there is a way to get arg name 'func_main_a' only from the sub function f1 without using a Wrapper(from varname.helpers).
"only from the sub function f1" meaning is:
```python
def func(func_p1):
    def f1():
        ... # can only write code here
        print(func_p1_argname)

    return f1
```

**Comment by pwwang** [comment]
The only possibility is that `f1` has the same signature as `func`. Imagine that when you do this:

```python
def func_main():
    func_main_a= 2
    f1 = func(func_main_a)
    f1()   # <- f1 called

func_main()
```

If we want to retrieve something while `f1` is getting called, it must be on the path (from where it's called to the function body). However, in your case, `f1` is called in the highlighted line above, and then the body of `f1` gets executed. You may see that there is no information about `func_main_a` on this path.

The `frame` and `func` arguments of `argname()` are designed for the scenario where the target function is decorated, which is actually similar to your case, but `f1` with the same signature as `func`. In such a case, you have to pass `func_main_a` to `f1` so that it's attached to the path and makes it possible for us to retrieve it inside the body of `f1`.

**Comment by stemalomd** [comment]
> You may see that there is no information about func_main_a on this path.

I think i may understand what you mean.
First, i simplified the code to:
```py
from varname import argname, nameof


def func(b):
    def f1():
        print(argname(nameof(b)))

    return f1


def main():
    a = 2
    f = func(a)
    f()


main()
```
When the program executes, stack might work like this:
(1)
stack 2: call func, and send variable a to func parameter b, return f1
stack 1: call main
(2)
stack 2': call f1, nameof(b)='b', execute argname('b') (here's the easy expression)
stack 1: call main

But stack 2 has been popped, so it is impossible to know where the parameter b comes from in stack 2', so cause an exception to be thrown.

and i think the solution you offer is:
```py
def func():
    def f1(b):
        print(argname(nameof(b))) # output: a
        #or: print(nameof(b, frame=2))

    return f1

def main():
    a = 2
    f = func()
    f(a)


main()
```
But the function f in the function main needs to be called frequently, so it is not suitable to pass in parameters every time.

I find another way:
(save the argument name to 'name' before stack pop of calling the func)
```py
def func(b):
    def f1():
        def f2():
            print(name)

        name = nameof(b, frame=3) # output: a
        #or: name = argname(nameof(b), frame=2)

        return f2

    return f1()


def main():
    a = 2
    f = func(a)
    f()


main()
```
But this is more complicated and stupid, so the original solution is simpler.
original solution:
```py
def func(b):
    def f1():
        print(name)

    name = argname(nameof(b))  # output: a
    return f1
```
lastly, thank you very much for your help

**Comment by pwwang** [comment]
First of all, the most misunderstood thing is `nameof()`, which LITERALLY only gives you the string representation of what's passed in. It has no ability to track other frames other than where it's directly called (the `frame` is designed for wrapper/decorator). 

In any other cases, `argname()` should be used.

**Comment by stemalomd** [comment]
you mean:
pass the variable in frame=x, and want get variable name in frame=x, that should use nameof().
pass the variable in frame=x, and want get variable name in frame=x+y, y>0 that should use argname().

explain: frame 1 is near the bottom of the stack, frame 2 is near the top of the stack

I don't understand the meaning of the code at the bottom, some variables are unbound. 
then I think you want to get variable name 'x' through nameof(c, frame=...) ?

**Comment by pwwang** [comment]
The code at the bottom is just to show an ambiguous case. 

Never mind. The rule is that you have to have the variable along the path, otherwise we are not able to retrieve it.

**Comment by stemalomd** [comment]
Because the questions I asked at the beginning have been solved, as for the questions discussed later, if I have a chance in the future, I will still ask you for advice, thx
