### ISSUE TITLE
argname doesn't seem to function, "cannot retrieve the node where the function is called"

### ISSUE THREAD

**Issue by xCqrbon** [pwwang/python-varname#93]
hello, i'm implementing argname into my code but it didn't seem to work. decided to run the example code on a new module as a test, however i got the same error.
(using pyscripter IDE)
```
from varname import argname

def func(a, b=1):
    print(argname('a'))

x = y = z = 2
func(x) # prints: x
```
i get the error: 
AppData\Local\Programs\Python\Python39\lib\site-packages\varname\core.py", line 445, in argname
    raise VarnameRetrievingError(
varname.utils.VarnameRetrievingError: Cannot retrieve the node where the function is called.

please let me know if i'm missing something simple

**Comment by pwwang** [comment]
Could you indicate the environment you ran the code? For example, python REPL, ipython, python script file, etc.

**Comment by xCqrbon** [comment]
it was a python script file

**Comment by pwwang** [comment]
Sorry, didn't see that you were using pyscripter IDE. I am not a user of it and am not sure how it runs code. My guess is that it uses something like `eval`, which we can't retrieve the source from.

**Comment by xCqrbon** [comment]
i see. thank you

**Comment by xCqrbon** [comment]
just one last thing, ignoring this specific IDE's issue, if i turn the file into an executable using PyInstaller, will there be any problems?

**Comment by pwwang** [comment]
By default, we can't retrieve the source code, since PyInstaller compiles the source into .pyc files. 
However, there seems to be tricks to do this:

https://stackoverflow.com/a/63448585/5088165

See if you want to give it a try.

**Comment by xCqrbon** [comment]
thank you very much! have a good day
