### ISSUE TITLE
How to print the variable names inside a for loop ?

### ISSUE THREAD

**Issue by abokey1** [pwwang/python-varname#94]
```
from varname import nameof

var1 = 1
var2 = 2
var3 = 3

inputs = [var1, var2, var3]

for i in inputs:
    print(nameof(i))
```

The code above prints three times the literal string `"i"` instead of printing the strings `"var1"`, `"var2"` and `"var3"`.

Is there a way to handle that, please ?

**Comment by pwwang** [comment]
```python
In [1]: from varname.helpers import Wrapper

In [2]: var1 = Wrapper(1)

In [3]: var2 = Wrapper(2)

In [4]: var3 = Wrapper(3)

In [5]: inputs = [var1, var2, var3]

In [6]: for v in inputs:
   ...:     print(v.name, v.value)
   ...: 
var1 1
var2 2
var3 3

```

**Comment by abokey1** [comment]
@pwwang, thank you so much!
Is there a more dynamic way to wrap the variables ?
Suppose we have dozens of variables, it would be more complicated to write dozens of wrappers/lines..

**Comment by pwwang** [comment]
Can you elaborate "more dynamic way"?

**Comment by abokey1** [comment]
Sure! Let's suppose we have a list carrying dozens of variables :
L = [var1, var2, var3, var4, var5, var6, ..]

Those variables could be of any type (str, int, pd.DataFrame, ..).

So even if we know beforehand their types/names/values, it will take forever to wrap them. Do you see what I mean ?

**Comment by pwwang** [comment]
Let me explain how this package works. Basically, we track where the variable is defined, such as, by assignment (`x = ...`) or function call (`func(var1, var2, ...)`. It makes us possible to retrieve the source, and then the variable names from the source/AST. 

Just want to confirm where your variable names are defined/initiated/created. Are they created literally, like you wrote: `L = [var1, ...]`, or dynamically: `L = []; L.append(var1); ...`?

**Comment by abokey1** [comment]
They're created like so :

var1 = 5
var2 = "foo"
var3 = pd.DataFrame()
var4 = {"a": 1, "b": 2}

And finally the list carrying all the variables :
L = [var1, var2, var3, var4]

**Comment by pwwang** [comment]
We can either use `Wrapper` or `argname`:

```python
from varname import argname

def foo(*args):
  names = argname("args")
  for name, arg in zip(names, args):
    print(name, arg)

var1 = 1
var2 = 2
var3 = 3

foo(var1, var2, var3)

# var1 1
# var2 2
# var3 3
```
