### ISSUE TITLE
Partial assignment in case a starred variable is present

### ISSUE THREAD

**Issue by sjorsdonkers** [pwwang/python-varname#96]
Hi,
In the case that there are properly named variables, but also a stared variable.
Would it be possible to be able to get the name for the named variables?

For example to make this work (currently it throws and exception(also when `raise_exc=False`)):
```python
from varname import varname

a, *_ = varname(frame=0, multi_vars=True)
assert a == 'a'
```
`_` Could be assigned None

**Comment by pwwang** [comment]
I never expected `varname()` to work with `frame=0`, it works anyway though.

However, it's a little bit confusing to me in your case. We could have:

```python
a, b = varname(frame=0, multi_vars=True)
# assert a == 'a'
# assert b == 'b'
```

But in your case, what are you expecting `_` to be? What we have in the AST for `_` is `Starred(value=Name(id='_', ctx=Store())`. Do you expect `_` to be `"_"`? If so:

```python
a, *_ = varname(frame=0, multi_vars=True)
# assert a == 'a'
# assert _ == '_'
```

```python
a, _ = varname(frame=0, multi_vars=True)
# Note that `_` instead of `*_` would have the same results:
# assert a == 'a'
# assert _ == '_'
```

I am not sure if this is what you actually wanted:

```python
def func():
    a, *_ = varname(multi_vars=True)
    print(a, _)
    return 1, 2, 3

x, y, z = func()
# prints: 'z', ['y', 'z']
# assert x == 1
# assert y == 2
# assert z == 3
```

**Comment by sjorsdonkers** [comment]
@pwwang Thanks for the quick follow up!

Using `frame=0` was to shorten the example, but it was actually just more confusing.
Here is the example based on your fragments:
```python
def func():
    a = varname(multi_vars=True)
    print(a)
    return 1, 2, 3

x, *_= func()
# prints: ['x', '*_'], or ['x', '_'], or ['x', '_', '_'], or ['x', None], or ..
assert x == 1
assert _ == [2, 3]
```

What I would like to achieve is that:
1. I get the name of `x`
2. I know there was a starred variable, such that I can handle (generate random names for) them myself.

Currently I am unable to get the name out of `x`, since `a = varname(multi_vars=True)` throws an exception due to the `*_`.

**Comment by sjorsdonkers** [comment]
If it would works as follows that would also be great:
```python
def func():
    a = varname(multi_vars=True, ignore_starred=True)
    print(a)
    return 1, 2, 3

x, *_= func()
# prints: ['x']
```

**Comment by pwwang** [comment]
I am leaning towards `['x', '*_']`.

**Comment by pwwang** [comment]
Supported by [v0.11.1](https://github.com/pwwang/python-varname/releases/tag/0.11.1)

**Comment by sjorsdonkers** [comment]
Awesome, thanks!
