### ISSUE TITLE
"Unable to retrieve the ast node" issue

### ISSUE THREAD

**Issue by slu216** [pwwang/python-varname#99]
Hi,

Could I get some help with the following ?
I am doing a dry run with the example script and hitting the following errors, was hitting similar issue when I tried argname, but nameof works fine here. It's running on M1 Mac.

```
> >>> from varname.helpers import register
> >>> @register
> ... def function():
> ...     return __varname__
> ...
> >>> func = function()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/slu/Library/Python/3.9/lib/python/site-packages/varname/helpers.py", line 75, in wrapper
>     cls_or_func.__globals__["__varname__"] = varname(
>   File "/Users/slu/Library/Python/3.9/lib/python/site-packages/varname/core.py", line 108, in varname
>     raise VarnameRetrievingError("Unable to retrieve the ast node.")
> varname.utils.VarnameRetrievingError: Unable to retrieve the ast node.
```

**Comment by pwwang** [comment]
Is this running via python raw REPL? e.g. Launched by `$ python` directly.

**Comment by slu216** [comment]
@pwwang, yes, it was using raw REPL. If this is a problem, it there a way to get workaround it in the case that I have to use REPL for some other reason?

**Comment by pwwang** [comment]
See https://github.com/pwwang/python-varname/issues/86#issuecomment-1236187444

**Comment by slu216** [comment]
thx for quickly addressing the issue, using ipython interactive works here.
